name: hr-talent-admin
on: push
jobs:
  deploy:
    name: 'Deploy hr-talent-admin'
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/develop'
    env:
      PROFILE_ACTIVE: prod
      GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
      APP_NAME: ${{ secrets.APP_NAME }}
      INSTANCE_ZONE: ${{ secrets.INSTANCE_ZONE}}
      REPOSITRORY: ${{ secrets.REGION }}-docker.pkg.dev
      IMAGE_URL: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.APP_NAME }}/${{ secrets.APP_NAME }}:latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
      - name: 'Docker auth configuration'
        run: gcloud auth configure-docker
      - name: 'Build image'
        run: docker build . --tag $IMAGE_URL
      - name: 'Docker push image'
        run: |-
          gcloud auth configure-docker $REPOSITRORY
          docker push "$IMAGE_URL"
      - name: 'Deploy project'
        run: |-
          gcloud compute instances update-container $APP_NAME \
          --zone $INSTANCE_ZONE \
          --container-image $IMAGE_URL \
          --container-env API_URL="$API_URL"
